---
- name: setup website
  hosts: web-servers
  become: yes
  become_user: root
  tasks:
  - block:
    - name: Install httpd package
      yum: name=httpd state=latest
  - block:
    - name: firewalld permits http service
      firewalld: service=http permanent=true state=enabled
  - block:
    - name: httpd enabled and running
      service: name=httpd enabled=true state=running
    - name: firewalld enabled and running
      service: name=firewalld enabled=true state=restarted
  - block:
    - name: Test HTML page
      shell: echo "Welcome to Ansible test page" > /var/www/html/index.html
- name: Test website
  hosts: web-servers
  become: yes
  become_user: root
  tasks:
   - name: latest python-httplib2 version installed
     yum: name=python-httplib2 state=latest
   - name: Verify the web server
     uri: url=http://localhost status_code=200  

